name: Build
on:
    pull_request:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            PUBLISH_SUFFIX: snapshots
            MAVEN_USER: ${{ secrets.MAVEN_USER }}
            MAVEN_PASS: ${{ secrets.MAVEN_PASS }}
            MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
            CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
            PATCH_NUMBER: ${{ github.event.inputs.patch }}
            PUBLISHING: ${{ github.event.inputs.publish }}
        steps:
            -   name: Checkout Repository
                uses: actions/checkout@main

            - name: Set up JDK 21
              uses: actions/setup-java@main
              with:
               distribution: 'temurin'
               java-version: '21'
          
            -   name: Setup Gradle
                uses: gradle/actions/setup-gradle@main
                with:
                  cache-read-only: false

            -   name: Build
                run: ./gradlew build

            -   name: Capture build artifacts
                uses: actions/upload-artifact@main
                with:
                    name: Artifacts
                    path: build/libs/
